import { useState, useEffect } from 'react';
import { X, Download, Loader2, GraduationCap } from 'lucide-react';
import { generateStudyGuide } from '../services/gemini';
import { useAuthStore } from '../stores/authStore';
import type { HomeworkResult } from '../types';
import toast from 'react-hot-toast';
import jsPDF from 'jspdf';

interface StudyGuideModalProps {
  homeworkItems: HomeworkResult[];
  onClose: () => void;
}

export default function StudyGuideModal({ homeworkItems, onClose }: StudyGuideModalProps) {
  const { profile } = useAuthStore();
  const [studyGuide, setStudyGuide] = useState<string>('');
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    const generateGuide = async () => {
      if (!profile?.selectedLanguage) {
        toast.error('Please select a language first');
        onClose();
        return;
      }

      setLoading(true);
      try {
        const items = homeworkItems.map((hw) => ({
          originalText: hw.originalText,
          explanation: hw.explanation,
          subject: hw.subject,
        }));

        const guide = await generateStudyGuide(
          items,
          profile.selectedLanguage,
          profile.gradeLevel
        );
        setStudyGuide(guide);
      } catch (error) {
        console.error('Study guide generation failed:', error);
        toast.error('Failed to generate study guide');
        onClose();
      } finally {
        setLoading(false);
      }
    };

    generateGuide();
  }, [homeworkItems, profile?.selectedLanguage, profile?.gradeLevel, onClose]);

  const handleDownloadPDF = () => {
    try {
      const doc = new jsPDF();
      const pageWidth = doc.internal.pageSize.getWidth();
      const pageHeight = doc.internal.pageSize.getHeight();
      const margin = 20;
      const maxWidth = pageWidth - 2 * margin;
      let yPosition = margin;

      // Title
      doc.setFontSize(20);
      doc.setFont('helvetica', 'bold');
      doc.text('Study Guide', margin, yPosition);
      yPosition += 10;

      // Grade Level
      if (profile?.gradeLevel) {
        doc.setFontSize(10);
        doc.setFont('helvetica', 'normal');
        doc.setTextColor(100, 100, 100);
        doc.text(`Grade Level: ${profile.gradeLevel}`, margin, yPosition);
        yPosition += 6;
      }

      // Date
      doc.setFontSize(10);
      doc.setFont('helvetica', 'normal');
      doc.setTextColor(100, 100, 100);
      doc.text(new Date().toLocaleDateString(), margin, yPosition);
      yPosition += 15;

      // Reset color for content
      doc.setTextColor(0, 0, 0);

      // Content
      doc.setFontSize(11);
      const lines = doc.splitTextToSize(studyGuide, maxWidth);

      lines.forEach((line: string) => {
        // Check if we need a new page
        if (yPosition > pageHeight - margin) {
          doc.addPage();
          yPosition = margin;
        }

        // Check for section headings (all caps lines)
        const isHeading = line.trim().length > 0 && line.trim() === line.trim().toUpperCase() && !line.startsWith('-');

        if (isHeading) {
          doc.setFont('helvetica', 'bold');
          doc.setFontSize(12);
          doc.text(line, margin, yPosition);
          doc.setFontSize(11);
        } else {
          doc.setFont('helvetica', 'normal');
          doc.text(line, margin, yPosition);
        }

        yPosition += 7;
      });

      // Footer
      const totalPages = doc.getNumberOfPages();
      for (let i = 1; i <= totalPages; i++) {
        doc.setPage(i);
        doc.setFontSize(8);
        doc.setFont('helvetica', 'italic');
        doc.setTextColor(100, 100, 100);
        doc.text(
          `Generated by Clarify - Page ${i} of ${totalPages}`,
          pageWidth / 2,
          pageHeight - 10,
          { align: 'center' }
        );
      }

      doc.save(`study-guide-${new Date().toISOString().split('T')[0]}.pdf`);
      toast.success('Study guide downloaded!');
    } catch (error) {
      console.error('PDF generation failed:', error);
      toast.error('Failed to download PDF');
    }
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/50 p-4">
      <div className="relative flex h-full max-h-[90vh] w-full max-w-3xl flex-col rounded-2xl bg-white shadow-2xl">
        {/* Header */}
        <div className="flex items-center justify-between border-b border-gray-200 p-6">
          <div className="flex items-center gap-3">
            <div className="flex h-10 w-10 items-center justify-center rounded-full bg-primary-100">
              <GraduationCap className="h-6 w-6 text-primary-600" />
            </div>
            <div>
              <h2 className="text-xl font-bold text-gray-900">Study Guide</h2>
              <p className="text-sm text-gray-500">
                Based on {homeworkItems.length} homework item{homeworkItems.length !== 1 ? 's' : ''}
                {profile?.gradeLevel && ` • ${profile.gradeLevel}`}
              </p>
            </div>
          </div>
          <button
            onClick={onClose}
            className="rounded-lg p-2 text-gray-400 transition-colors hover:bg-gray-100 hover:text-gray-600"
          >
            <X className="h-5 w-5" />
          </button>
        </div>

        {/* Content */}
        {loading ? (
          <div className="flex flex-1 flex-col items-center justify-center gap-4 p-12">
            <div className="relative">
              <div className="flex h-20 w-20 items-center justify-center rounded-2xl bg-primary-100">
                <GraduationCap className="h-10 w-10 text-primary-600" />
              </div>
              <Loader2 className="absolute -right-2 -top-2 h-8 w-8 animate-spin text-primary-500" />
            </div>
            <div className="text-center">
              <h3 className="text-lg font-semibold text-gray-900">Generating your study guide...</h3>
              <p className="mt-1 text-sm text-gray-500">This may take a moment</p>
            </div>
          </div>
        ) : (
          <>
            <div className="flex-1 overflow-y-auto p-6">
              <div className="prose prose-sm max-w-none">
                <div className="whitespace-pre-wrap text-gray-700">{studyGuide}</div>
              </div>
            </div>

            {/* Footer */}
            <div className="border-t border-gray-200 p-6">
              <button
                onClick={handleDownloadPDF}
                className="flex w-full items-center justify-center gap-2 rounded-lg bg-primary-600 px-6 py-3 font-semibold text-white shadow-md transition-all hover:bg-primary-700 hover:shadow-lg"
              >
                <Download className="h-5 w-5" />
                Download as PDF
              </button>
            </div>
          </>
        )}
      </div>
    </div>
  );
}
